services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true


    Twig\Loader\FilesystemLoader:
        arguments:
            - '%path.root%/src/Application/Template'

    Twig\Environment:
        arguments:
            - '@Twig\Loader\FilesystemLoader'
            
    Application\Controller\:
        resource: '%path.root%\src\Application\Controller\*'

    Application\Controller\Hello: # Why this line must be exits? If I remove it, I get "You have requested a non-existent service" error