services:

    _defaults:
        autowire: false
        autoconfigure: false
        public: true


    Twig\Loader\FilesystemLoader:
        arguments:
            - '%path.root%/Application/Template'

    Twig\Environment:
        arguments:
            - '@Twig\Loader\FilesystemLoader'
            
    Application\Controller\Hello:
        class: Application\Controller\Hello
        arguments:
            - '@Twig\Environment'

