services:
    Application\Controller\Hello:
        class: Application\Controller\Hello

    Twig\Loader\FilesystemLoader:
        arguments:
            - '%path.root%/Application/Template'

    Twig\Environment:
        arguments:
            - '@Twig\Loader\FilesystemLoader'