services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true


    Twig\Loader\FilesystemLoader:
        arguments:
            - '%path.root%/src/Application/Template'

    Twig\Environment:
        arguments:
            - '@Twig\Loader\FilesystemLoader'
            
    Application\Controller\:
        resource: '%path.root%/src/Application/Controller/*'
    
    Model\Service\:
        resource: '%path.root%/src/Model/Service/*'
        
    Model\Mapper\:
        resource: '%path.root%/src/Model/Mapper/*'

    PDO:
        class: PDO
        arguments: ['mysql:host=localhost;dbname=test;charset=utf8mb4', 'root', '']
        calls:
            - [setAttribute, [!php/const PDO::ATTR_ERRMODE, !php/const PDO::ERRMODE_EXCEPTION]]