services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true


    Twig\Loader\FilesystemLoader:
        arguments:
            - '%path.root%/src/Application/Template'

    Twig\Environment:
        arguments:
            - '@Twig\Loader\FilesystemLoader'
            
    Application\Controller\:
        resource: '%path.root%/src/Application/Controller/*'