# routes.yaml

home:
  path: /
  defaults: 
    controller: Application\Controller\Hello
    action: index
    name: World
    middlewares: [Accessibility]

hello:
  path: /hello/{name}
  defaults: 
    controller: Application\Controller\Hello
    action: index
    name: Sajad

bye:
  path: /bye
  defaults: 
    controller: Application\Controller\Bye
    action: index